export type {
  AiStatus,
  AnswerState,
  AnswerStatus,
  C2SMessage,
  DecidedBy,
  GameSettings,
  GameState,
  Language,
  Phase,
  PlayerState,
  RoundState,
  S2CMessage,
} from '@alto-lapiz/shared';
export {
  DEFAULT_CATEGORIES,
  DEFAULT_SETTINGS,
  LANGUAGES,
  LANGUAGE_NAMES,
  MAX_ANSWER_LEN,
  MAX_CATEGORIES,
  MAX_CATEGORY_LEN,
  MAX_NAME_LEN,
  MAX_ROUNDS,
  MAX_TIME_LIMIT,
  MIN_CATEGORIES,
  MIN_TIME_LIMIT,
} from '@alto-lapiz/shared';
